version: 2

aliases:
  - &defaults
    working_directory: ~/dotsync
    docker:
      - image: circleci/node:10
  - &tag
    tags:
      only: /^v\d+\.\d+\.\d+(-\S*)?$/
  - &tag-filter
    filters: *tag

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build: *tag-filter
      - test:
          <<: *tag-filter
          requires:
            - build
      - lint:
          <<: *tag-filter
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            <<: *tag
            branches:
              ignore: /.*/

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - packages/@dotsync/app/node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint

  release:
    <<: *defaults
    environment:
      ELECTRON_CACHE: ~/.cache/electron
      ELECTRON_BUILDER_CACHE: ~/.cache/electron-builder
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          name: Restore Electron Cache
          keys:
            - electron-cache
      - run:
          name: Release
          command: |
            cd packages/@dotsync/app
            # yarn build:electron
      - save_cache:
          name: Save Electron Cache
          key: electron-cache
          paths:
            - ~/.cache/electron
            - ~/.cache/electron-builder
