name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]
jobs:
  ci:
    name: CI
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: exit 0
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 10
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 10
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
